import type { SiteContent } from './types'

export const siteContent: SiteContent = {
  profile: {
    name: 'Matheus Fugisaki',
    title: {
      pt: 'Desenvolvedor Front-end Sênior',
      en: 'Senior Front-end Developer',
    },
    bio: {
      pt: 'Desenvolvedor front-end sênior. Construo interfaces modernas com React, Next.js, Tailwind CSS e TypeScript.',
      en: 'Senior front-end developer. I build modern interfaces with React, Next.js, Tailwind CSS and TypeScript.',
    },
    avatar: '/profile/avatar.jpg',
    socials: [
      { platform: 'github', url: 'https://github.com/fugisakimatheus' },
      { platform: 'linkedin', url: 'https://linkedin.com/in/matheus-fugisaki' },
      { platform: 'instagram', url: 'https://instagram.com/fugisakimatheus' },
    ],
  },
  career: [
    {
      id: 'nexgy',
      company: 'Nexgy',
      role: {
        pt: 'Desenvolvedor Front-end Sênior',
        en: 'Senior Front-end Developer',
      },
      period: { pt: 'Atual', en: 'Present' },
      description: {
        pt: 'Frontend com Next.js e TypeScript, focado em performance, qualidade de código e entrega contínua com TanStack Query, Zustand, Tailwind CSS, Vitest e Playwright.',
        en: 'Frontend with Next.js and TypeScript, focused on performance, code quality, and continuous delivery with TanStack Query, Zustand, Tailwind CSS, Vitest, and Playwright.',
      },
      technologies: [
        'React',
        'TypeScript',
        'Next.js',
        'Tailwind CSS',
        'TanStack Query',
        'Zustand',
        'Vitest',
        'Playwright',
      ],
      type: 'legal',
    },
    {
      id: 'objective',
      company: 'Objective',
      role: {
        pt: 'Desenvolvedor Front-end',
        en: 'Front-end Developer',
      },
      period: { pt: '2021 – 2024', en: '2021 – 2024' },
      description: {
        pt: 'Full-cycle com Angular, React/Next.js e React Native em TypeScript. Atuação em testes automatizados (Jest, Vitest, Cypress, Playwright), arquitetura (SOLID, DDD, Clean Architecture), design systems, gerenciamento de estado (RxJS, Redux, React Query) e DevOps (Docker, Firebase, CI/CD).',
        en: 'Full-cycle work with Angular, React/Next.js, and React Native in TypeScript. Experience in automated testing (Jest, Vitest, Cypress, Playwright), architecture (SOLID, DDD, Clean Architecture), design systems, state management (RxJS, Redux, React Query), and DevOps (Docker, Firebase, CI/CD).',
      },
      technologies: [
        'React',
        'TypeScript',
        'Next.js',
        'Angular',
        'React Native',
        'Tailwind CSS',
        'Jest',
        'Vitest',
        'Cypress',
        'Playwright',
        'Docker',
        'Firebase',
        'CI/CD',
      ],
      type: 'job',
    },
    {
      id: 'grandchef',
      company: 'GrandChef',
      role: {
        pt: 'Desenvolvedor Web Pleno',
        en: 'Web Developer Mid-level',
      },
      period: { pt: '2019 – 2021', en: '2019 – 2021' },
      description: {
        pt: 'Desenvolvedor frontend com experiência em Vue.js (Quasar, Vuex, GraphQL/Apollo) e React (TypeScript, Electron) com integração de hardware, além de prototipagem no Figma usando Material Design.',
        en: 'Frontend developer with experience in Vue.js (Quasar, Vuex, GraphQL/Apollo) and React (TypeScript, Electron) with hardware integration, as well as prototyping in Figma using Material Design.',
      },
      technologies: [
        'Vue',
        'Quasar',
        'Vuex',
        'GraphQL',
        'React',
        'TypeScript',
        'Next.js',
        'Tailwind CSS',
        'Electron',
      ],
      type: 'job',
    },
    {
      id: 'resenhe',
      company: 'Resenhe',
      role: {
        pt: 'Desenvolvedor Front-end Júnior',
        en: 'Junior Front-end Developer',
      },
      period: { pt: '2018 – 2019', en: '2018 – 2019' },
      description: {
        pt: 'Desenvolvedor Full Stack com experiência em mobile com React Native (StyleSheet) e no backend com Node.js, Express.js e MongoDB (Mongoose).',
        en: 'Full Stack Developer with experience in mobile using React Native (StyleSheet) and in backend development using Node.js, Express.js, and MongoDB (Mongoose).',
      },
      technologies: [
        'React Native',
        'TypeScript',
        'Node.js',
        'Express.js',
        'MongoDB',
        'Mongoose',
        'Git',
      ],
      type: 'part-time',
    },
  ],
  projects: [
    {
      id: 'strategy-pattern-example',
      title: { pt: 'Strategy pattern', en: 'Strategy pattern' },
      description: {
        pt: 'Exemplo do padrão Strategy em React com TypeScript.',
        en: 'Strategy design pattern example in React with TypeScript.',
      },
      image: '/projects/strategy-pattern-example.png',
      repoUrl: 'https://github.com/fugisakimatheus/strategy-pattern-example',
      tags: ['React', 'TypeScript', 'Patterns'],
      imageAspect: 1480 / 963,
      featured: true,
    },
    {
      id: 'currency-converter',
      title: { pt: 'Conversor de moedas', en: 'Currency converter' },
      description: {
        pt: 'Aplicativo React para conversão de moedas em tempo real.',
        en: 'React app for real-time currency conversion.',
      },
      image: '/projects/currency-converter.png',
      imageAspect: 1491 / 963,
      repoUrl: 'https://github.com/fugisakimatheus/currency-converter',
      tags: ['React', 'TypeScript'],
      featured: true,
    },
    {
      id: 'energy-dashboard',
      title: { pt: 'Energy dashboard', en: 'Energy dashboard' },
      description: {
        pt: 'Dashboard de dados de energia construído com Next.js e TypeScript.',
        en: 'An energy data dashboard built with Next.js and TypeScript.',
      },
      image: '/projects/energy-dashboard.png',
      imageAspect: 1686 / 959,
      repoUrl: 'https://github.com/fugisakimatheus/energy-dashboard',
      tags: ['Next.js', 'TypeScript', 'Dashboard'],
      featured: true,
    },
    {
      id: 'code-hero-angular',
      title: { pt: 'Code hero', en: 'Code hero' },
      description: {
        pt: 'Catálogo de personagens Marvel consumindo API pública, feito com Angular.',
        en: 'Marvel characters catalog using a public API, built with Angular.',
      },
      image: '/projects/code-hero-angular.png',
      repoUrl: 'https://github.com/fugisakimatheus/code-hero-angular',
      tags: ['Angular', 'TypeScript', 'API'],
      featured: true,
    },
    {
      id: 'react-anime-calculator',
      title: { pt: 'Calculadora anime', en: 'Anime calculator' },
      description: {
        pt: 'Calculadora temática em React com animações e interface customizada.',
        en: 'Themed React calculator with animations and a custom interface.',
      },
      image: '/projects/react-anime-calculator.jpeg',
      repoUrl: 'https://github.com/fugisakimatheus/react-anime-calculator',
      tags: ['React', 'TypeScript'],
      featured: false,
    },
  ],
  skills: [
    { name: 'React', category: 'frontend', icon: 'react' },
    { name: 'TypeScript', category: 'frontend', icon: 'typescript' },
    { name: 'Next.js', category: 'frontend', icon: 'nextdotjs' },
    { name: 'React Native', category: 'frontend', icon: 'react' },
    { name: 'Angular', category: 'frontend', icon: 'angular' },
    { name: 'Vue', category: 'frontend', icon: 'vue' },
    { name: 'Quasar', category: 'frontend', icon: 'quasar' },
    { name: 'Vuex', category: 'frontend', icon: 'vue' },
    { name: 'Tailwind CSS', category: 'frontend', icon: 'tailwindcss' },
    { name: 'Sass', category: 'frontend', icon: 'sass' },
    { name: 'TanStack Query', category: 'frontend', icon: 'reactquery' },
    { name: 'Zustand', category: 'frontend', icon: 'zustand' },
    { name: 'GraphQL', category: 'frontend', icon: 'graphql' },
    { name: 'Node.js', category: 'tools', icon: 'nodedotjs' },
    { name: 'Express.js', category: 'tools', icon: 'express' },
    { name: 'Bun', category: 'tools', icon: 'bun' },
    { name: 'Vite', category: 'tools', icon: 'vite' },
    { name: 'Git', category: 'tools', icon: 'git' },
    { name: 'Docker', category: 'tools', icon: 'docker' },
    { name: 'Firebase', category: 'tools', icon: 'firebase' },
    { name: 'Electron', category: 'tools', icon: 'electron' },
    { name: 'MongoDB', category: 'tools', icon: 'mongodb' },
    { name: 'Mongoose', category: 'tools', icon: 'mongoose' },
    { name: 'Vitest', category: 'testing', icon: 'vitest' },
    { name: 'Jest', category: 'testing', icon: 'jest' },
    { name: 'Playwright', category: 'testing', icon: 'playwright' },
    { name: 'Cypress', category: 'testing', icon: 'cypress' },
  ],
  contact: {
    email: 'matheusgfmaciel@gmail.com',
    github: 'https://github.com/fugisakimatheus',
    linkedin: 'https://linkedin.com/in/matheus-fugisaki',
    instagram: 'https://instagram.com/fugisakimatheus',
  },
}
